# Generated by Django 4.2 on 2025-12-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='job_type',
            field=models.CharField(choices=[('FETCH_TODAY', "Fetch Today's Market Data"), ('COMPUTE_FEATURES', 'Compute Features'), ('TRAIN_MODEL', 'Train ML Model'), ('EVENING_PREDICT', 'Evening Prediction'), ('MORNING_CONFIRM', 'Morning Confirmation'), ('INSTRUMENT_SYNC', 'Sync Instruments')], max_length=50),
        ),
    ]
