# Generated by Django 4.2 on 2025-12-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobstatus_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='job_type',
            field=models.CharField(choices=[('FETCH_TODAY', "Fetch Today's Market Data"), ('COMPUTE_FEATURES', 'Compute Features'), ('TRAIN_MODEL', 'Train ML Model'), ('EVENING_PREDICT', 'Evening Prediction'), ('MORNING_CONFIRM', 'Morning Confirmation'), ('INSTRUMENT_SYNC', 'Sync Instruments'), ('historical_backfill', 'Historical Data Backfill'), ('sync_holidays', 'Sync NSE Holidays'), ('MORNING_INFERENCE', 'Morning Inference'), ('OUTCOME_EVALUATION', 'Outcome Evaluation'), ('METRICS_COMPUTATION', 'Metrics Computation')], max_length=50),
        ),
    ]
