# Generated by Django 4.2 on 2025-12-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prob_up', models.FloatField()),
                ('confidence', models.FloatField()),
                ('entry', models.FloatField()),
                ('target', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('close', models.FloatField()),
                ('vwap', models.FloatField()),
                ('atr_14', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('ts', models.DateTimeField()),
                ('feature_hash', models.CharField(max_length=64)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument')),
            ],
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['date'], name='mlapp_predi_date_87adac_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['instrument'], name='mlapp_predi_instrum_31c326_idx'),
        ),
    ]
