# Generated by Django 4.2 on 2025-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_finalpickhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('symbols', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('win_rate', models.FloatField()),
                ('total_trades', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('zeroes', models.IntegerField()),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
