# Generated by Django 4.2 on 2025-12-25 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0003_backtesthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyOptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('best_params', models.JSONField()),
                ('best_metrics', models.JSONField()),
                ('best_score', models.FloatField()),
                ('all_results', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
