# Generated by Django 4.2 on 2025-12-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0004_strategyoptimizationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningInferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('model_version', models.CharField(max_length=255)),
                ('symbols', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
