# Generated by Django 4.2 on 2025-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0005_morninginferencerun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=50)),
                ('probability', models.FloatField()),
                ('rank', models.IntegerField()),
                ('model_version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TradeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=32)),
                ('model_version', models.CharField(max_length=128)),
                ('prediction_time', models.DateTimeField()),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(choices=[('TP', 'Target Hit'), ('SL', 'Stop Loss Hit'), ('TIMEOUT', 'Timeout'), ('INVALID', 'Invalid')], max_length=16)),
                ('holding_minutes', models.IntegerField(default=0)),
                ('tp_price', models.FloatField(blank=True, null=True)),
                ('sl_price', models.FloatField(blank=True, null=True)),
                ('R_multiple', models.FloatField()),
                ('pnl_pct', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='tradeoutcome',
            index=models.Index(fields=['date'], name='mlapp_trade_date_ccfb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeoutcome',
            index=models.Index(fields=['symbol'], name='mlapp_trade_symbol_9dcd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeoutcome',
            index=models.Index(fields=['model_version'], name='mlapp_trade_model_v_9559c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradeoutcome',
            unique_together={('date', 'symbol', 'model_version')},
        ),
        migrations.AlterUniqueTogether(
            name='morningprediction',
            unique_together={('date', 'symbol')},
        ),
    ]
