# Generated by Django 4.2 on 2025-12-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_key', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('instrument_type', models.CharField(default='EQ', max_length=10)),
                ('tick_size', models.FloatField(default=0.05)),
                ('lot_size', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('interval', models.CharField(default='1minute', max_length=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument')),
            ],
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['instrument', 'ts'], name='market_cand_instrum_df87c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together={('instrument', 'ts', 'interval')},
        ),
    ]
