# Generated by Django 4.2 on 2025-12-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_upstoxtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBackfillState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(max_length=10)),
                ('last_fetched_date', models.DateField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('failed_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_state', to='market.instrument')),
            ],
        ),
    ]
