# Generated by Django 4.2 on 2025-12-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_historicalbackfillstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbackfillstate',
            name='completed_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbackfillstate',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbackfillstate',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbackfillstate',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
