# Generated by Django 4.2 on 2025-12-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_historicalbackfillstate_completed_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('exchange', models.CharField(default='NSE', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
