# Generated by Django 4.2 on 2025-12-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_tradingholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstoxtoken',
            name='refresh_token',
        ),
    ]
