# Generated by Django 4.2 on 2025-12-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_upstoxtoken_refresh_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalbackfillstate',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instrument'),
        ),
        migrations.AlterField(
            model_name='tradingholiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('instrument', 'ts', 'interval'), name='unique_candle_per_interval'),
        ),
        migrations.AddConstraint(
            model_name='historicalbackfillstate',
            constraint=models.UniqueConstraint(fields=('instrument', 'interval'), name='unique_backfill_state_per_interval'),
        ),
        migrations.AddConstraint(
            model_name='tradingholiday',
            constraint=models.UniqueConstraint(fields=('date', 'exchange'), name='unique_holiday_per_exchange'),
        ),
    ]
