# Generated by Django 4.2 on 2026-01-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_candle_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historicalbackfillstate',
            name='unique_backfill_state_per_interval',
        ),
        migrations.AddField(
            model_name='historicalbackfillstate',
            name='window_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='candle',
            name='interval',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalbackfillstate',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_states', to='market.instrument'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalbackfillstate',
            unique_together={('instrument', 'interval')},
        ),
        migrations.RemoveField(
            model_name='historicalbackfillstate',
            name='completed_days',
        ),
        migrations.RemoveField(
            model_name='historicalbackfillstate',
            name='total_days',
        ),
    ]
