# ---------------------------------------------------------
# Upstox API constants
# ---------------------------------------------------------


# Job types (used in DB + UI)
JOB_FETCH_TODAY = "FETCH_TODAY"
JOB_INSTRUMENT_SYNC = "INSTRUMENT_SYNC"
JOB_COMPUTE_FEATURES = "COMPUTE_FEATURES"
JOB_TRAIN_MODEL = "TRAIN_MODEL"
JOB_EVENING_PREDICT = "EVENING_PREDICT"
JOB_MORNING_CONFIRM = "MORNING_CONFIRM"
JOB_HISTORICAL_BACKFILL = "historical_backfill"
JOB_GAP_REPAIR = "gap_repair"
JOB_SYNC_HOLIDAYS = "sync_holidays"
JOB_MORNING_INFERENCE = "MORNING_INFERENCE"
JOB_OUTCOME_EVAL = "OUTCOME_EVALUATION"
JOB_METRICS_COMPUTE = "METRICS_COMPUTATION"


# Instrument types
INSTRUMENT_EQ = "EQ"
INSTRUMENT_INDEX = "INDEX"
INSTRUMENT_FUT = "FUT"
INSTRUMENT_OPT = "OPT"

# Exchanges
EXCHANGE_NSE = "NSE"
EXCHANGE_BSE = "BSE"

# Candle intervals
INTERVAL_1MIN = 1
INTERVAL_5MIN = 5

# Backfill defaults
BACKFILL_1MIN_YEARS = 1
BACKFILL_5MIN_YEARS = 3

MAX_BACKFILL_RETRIES = 5
RETRY_COOLDOWN_MINUTES = 30


